# Generated by Django 6.0.6 on 2026-06-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
